# Generated by Django 4.2.2 on 2023-06-23 10:09

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Prices",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("card_title", models.CharField(max_length=80)),
                ("card_text", models.CharField(max_length=500)),
                ("button_text", models.CharField(max_length=20)),
            ],
        ),
    ]
