# Generated by Django 4.2.2 on 2023-06-30 09:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("page_of_bouquet", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="prices",
            name="card_text",
            field=models.TextField(),
        ),
    ]
