# Generated by Django 4.2.2 on 2023-06-30 09:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("page_of_bouquet", "0002_alter_prices_card_text"),
    ]

    operations = [
        migrations.CreateModel(
            name="Card",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=80)),
                ("text", models.TextField()),
                ("price", models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name="Prices",
        ),
    ]
